{
  "Ethereum Mainnet": {
    "lastProcessedBlock": 21414948,
    "hasError": true,
    "lastUpdated": "2024-12-16T12:03:31.727Z",
    "lastError": "\n      ðŸš¨ FATAL ERROR PROCESSING BLOCK ðŸš¨\n      Block: 21414949\n      Error: exceeded maximum retry limit (request={  }, response={  }, error=null, info={ \"requestUrl\": \"https://eth.llamarpc.com\", \"responseBody\": \"error code: 1015\", \"responseStatus\": \"599 CLIENT ESCALATED SERVER ERROR (429 Too Many Requests; exceeded maximum retry limit)\" }, code=SERVER_ERROR, version=6.13.4)\n      Error: exceeded maximum retry limit (request={  }, response={  }, error=null, info={ \"requestUrl\": \"https://eth.llamarpc.com\", \"responseBody\": \"error code: 1015\", \"responseStatus\": \"599 CLIENT ESCALATED SERVER ERROR (429 Too Many Requests; exceeded maximum retry limit)\" }, code=SERVER_ERROR, version=6.13.4)\n    at makeError (/Users/sero/work/zksync-rss/packages/backend/node_modules/ethers/src.ts/utils/errors.ts:694:21)\n    at assert (/Users/sero/work/zksync-rss/packages/backend/node_modules/ethers/src.ts/utils/errors.ts:715:25)\n    at FetchResponse.assertOk (/Users/sero/work/zksync-rss/packages/backend/node_modules/ethers/src.ts/utils/fetch.ts:950:15)\n    at JsonRpcProvider._send (/Users/sero/work/zksync-rss/packages/backend/node_modules/ethers/src.ts/providers/provider-jsonrpc.ts:1245:18)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at <anonymous> (/Users/sero/work/zksync-rss/packages/backend/node_modules/ethers/src.ts/providers/provider-jsonrpc.ts:537:40)\n    "
  },
  "ZKSync": {
    "lastProcessedBlock": 51430251,
    "hasError": false,
    "lastUpdated": "2024-12-16T12:03:39.260Z"
  }
}